### Extracting patches from large images

In [1]:
import numpy as np
from matplotlib import pyplot as plt
from patchify import patchify
import tifffile as tiff
import cv2
import glob as glob
from PIL import Image
import os
from skimage.transform import resize
from tqdm import tqdm
import numpy as np
from patchify import patchify, unpatchify

In [3]:
#img_path = glob.glob('./data/군포지사/*.jpg')
img_path = './data/gunpo_image/'
img_ids = next(os.walk(img_path))[2]

In [61]:
img_ids

['GH020070.MP4_0.jpg',
 'GH020070.MP4_1.jpg',
 'GH020070.MP4_10.jpg',
 'GH020070.MP4_11.jpg',
 'GH020070.MP4_12.jpg',
 'GH020070.MP4_13.jpg',
 'GH020070.MP4_14.jpg',
 'GH020070.MP4_15.jpg',
 'GH020070.MP4_16.jpg',
 'GH020070.MP4_17.jpg',
 'GH020070.MP4_18.jpg',
 'GH020070.MP4_19.jpg',
 'GH020070.MP4_2.jpg',
 'GH020070.MP4_20.jpg',
 'GH020070.MP4_21.jpg',
 'GH020070.MP4_22.jpg',
 'GH020070.MP4_23.jpg',
 'GH020070.MP4_24.jpg',
 'GH020070.MP4_25.jpg',
 'GH020070.MP4_26.jpg',
 'GH020070.MP4_27.jpg',
 'GH020070.MP4_28.jpg',
 'GH020070.MP4_29.jpg',
 'GH020070.MP4_3.jpg',
 'GH020070.MP4_30.jpg',
 'GH020070.MP4_31.jpg',
 'GH020070.MP4_32.jpg',
 'GH020070.MP4_33.jpg',
 'GH020070.MP4_34.jpg',
 'GH020070.MP4_35.jpg',
 'GH020070.MP4_36.jpg',
 'GH020070.MP4_37.jpg',
 'GH020070.MP4_38.jpg',
 'GH020070.MP4_39.jpg',
 'GH020070.MP4_4.jpg',
 'GH020070.MP4_5.jpg',
 'GH020070.MP4_6.jpg',
 'GH020070.MP4_7.jpg',
 'GH020070.MP4_8.jpg',
 'GH020070.MP4_9.jpg',
 'GH030070.MP4_0.jpg',
 'GH030070.MP4_1.jpg',
 'GH

## 1. 한 차선을 기준으로 patch화

In [42]:
# 이미지 처음 1개만
# 경로에 한글 있으면 안됨
test = cv2.imread(img_path + img_ids[0], cv2.IMREAD_COLOR)

In [44]:
test.shape

(960, 31210, 3)

In [97]:
patches_img = patchify(test, (320,320,3), step=320) # patch shape [6,6,3]
print(patches_img.shape)

(3, 97, 1, 320, 320, 3)


In [45]:
save_path = './data/patch image/'
for i in range(patches_img.shape[0]):
    for j in range(patches_img.shape[1]):
        single_patch_img = patches_img[i,j,:,:]
        tiff.imwrite(save_path + 'image_' + str(0) + '_' + str(i)+str(j)+ ".tiff", single_patch_img)

In [46]:
# 가로로 정확하게 안 나눠떨어짐 -> 가로가 조금 짤리는 건 괜찮다
31210 / 320

97.53125

In [48]:
# # 첫번째 이미지만 
# for idx in range(1):
#     img = Image.open(img_path[idx])
#     image = np.array(img)
#     #iimage = image[0]
#     patches_img = patchify(image, (60,60,3), step=60) # patch shape [6,6,3]
#     print(patches_img.shape)
#     for i in range(patches_img.shape[0]):
#         for j in range(patches_img.shape[1]):
#             single_patch_img = patches_img[i,j,:,:]
#             tiff.imwrite(r'C:/Users/user/Desktop/한국도로공사/Image Segmentation/image/' + 'image_' + str(idx) + '_' + str(i)+str(j)+ ".tif", single_patch_img)

## 2. 세 차선을 전체로 보고 960 X 960 으로 patch화 후 resizing

In [4]:
#img_path = glob.glob('./data/군포지사/*.jpg')
img_path = './data/gunpo_image/'
img_ids = next(os.walk(img_path))[2]

In [5]:
# 경로에 한글 있으면 안됨
test2 = cv2.imread(img_path + img_ids[0], cv2.IMREAD_COLOR)

In [65]:
# patchify 후 저장
patches_img = patchify(test2, (960,960,3), step=960) # patch shape [6,6,3]
print(patches_img.shape)
save_path2 = './data/patch960 image/'
for i in range(patches_img.shape[0]):
    for j in range(patches_img.shape[1]):
        patch960_img = patches_img[i,j,:,:]
        tiff.imwrite(save_path2 + 'image_' + str(0) + '_' + str(i)+str(j)+ ".tiff", patch960_img)

(1, 32, 1, 960, 960, 3)


In [66]:
# resizing
final_path = './data/final image/'
img_ids = next(os.walk(save_path2))[2]
for i in tqdm(range(len(img_ids))):
    img = cv2.imread(save_path2 + img_ids[i], cv2.IMREAD_COLOR)
    final_img = cv2.resize(img,(512,512),interpolation = cv2.INTER_AREA)
    cv2.imwrite(final_path + 'image_' + str(0) + '_' + str(i) + ".jpg", final_img)

100%|██████████████████████████████████████████████████████████████████████████████████| 32/32 [00:01<00:00, 23.74it/s]


In [112]:
# 이미지 확인
cv2.imshow('resize_test',resize_test)
cv2.waitKey(0)
cv2.destroyAllWindows()

512

## 전체 이미지 시도

In [2]:
img_path = './data/gunpo_image/'
img_ids = next(os.walk(img_path))[2]

In [3]:
# 경로에 한글 있으면 안됨
for idx in tqdm(range(len(img_ids))):
    img = cv2.imread(img_path + img_ids[idx], cv2.IMREAD_COLOR)
    patches_img = patchify(img, (960,960,3), step=960) # patch shape [6,6,3]

    save_path2 = './data/patch960 image/'
    for i in range(patches_img.shape[0]):
        for j in range(patches_img.shape[1]):
            for p in range(patches_img.shape[2]):
                patch960_img = patches_img[i,j,p,:,:]
                cv2.imwrite(save_path2 + 'image_' + str(idx) + '_' + str(i)+str(j)+str(p)+ ".jpg", patch960_img)

100%|████████████████████████████████████████████████████████████████████████████████| 114/114 [03:29<00:00,  1.84s/it]


In [ ]:
# cv2.imshow('patches_img2',patches_img[0][0])
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [13]:
img_ids

['image_0_000.jpg',
 'image_0_010.jpg',
 'image_0_0100.jpg',
 'image_0_0110.jpg',
 'image_0_0120.jpg',
 'image_0_0130.jpg',
 'image_0_0140.jpg',
 'image_0_0150.jpg',
 'image_0_0160.jpg',
 'image_0_0170.jpg',
 'image_0_0180.jpg',
 'image_0_0190.jpg',
 'image_0_020.jpg',
 'image_0_0200.jpg',
 'image_0_0210.jpg',
 'image_0_0220.jpg',
 'image_0_0230.jpg',
 'image_0_0240.jpg',
 'image_0_0250.jpg',
 'image_0_0260.jpg',
 'image_0_0270.jpg',
 'image_0_0280.jpg',
 'image_0_0290.jpg',
 'image_0_030.jpg',
 'image_0_0300.jpg',
 'image_0_0310.jpg',
 'image_0_040.jpg',
 'image_0_050.jpg',
 'image_0_060.jpg',
 'image_0_070.jpg',
 'image_0_080.jpg',
 'image_0_090.jpg',
 'image_100_000.jpg',
 'image_100_010.jpg',
 'image_100_0100.jpg',
 'image_100_0110.jpg',
 'image_100_0120.jpg',
 'image_100_0130.jpg',
 'image_100_0140.jpg',
 'image_100_0150.jpg',
 'image_100_0160.jpg',
 'image_100_0170.jpg',
 'image_100_0180.jpg',
 'image_100_0190.jpg',
 'image_100_020.jpg',
 'image_100_0200.jpg',
 'image_100_0210.jp

In [12]:
# # resizing
# final_path = './data/final image/'
# img_ids = next(os.walk(save_path2))[2]
# for idx in tqdm(range(len(img_ids))):
#     img = cv2.imread(save_path2 + img_ids[idx], cv2.IMREAD_COLOR)
#     final_img = cv2.resize(img,(512,512),interpolation = cv2.INTER_AREA)
#     cv2.imwrite(final_path + 'image_' + str(idx) + '_' + str(i) + ".jpg", final_img)

100%|██████████████████████████████████████████████████████████████████████████████| 3648/3648 [02:15<00:00, 26.87it/s]


In [17]:
# resizing
final_path = './data/final image/'
img_ids = next(os.walk(save_path2))[2]
for idx, val in tqdm(enumerate(img_ids)):
    img = cv2.imread(save_path2 + img_ids[idx], cv2.IMREAD_COLOR)
    final_img = cv2.resize(img,(512,512),interpolation = cv2.INTER_AREA)
    cv2.imwrite(final_path + str(val) + '.jpg', final_img)

3648it [02:05, 29.04it/s]


### patchify 예시

In [211]:
# 2차원 이미지
image = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
patches = patchify(image, (2,2), step=1) # split image into 2*3 small 2*2 patches.

In [212]:
image.shape

(3, 4)

In [213]:
image

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [214]:
patches.shape

(2, 3, 2, 2)

In [215]:
patches

array([[[[ 1,  2],
         [ 5,  6]],

        [[ 2,  3],
         [ 6,  7]],

        [[ 3,  4],
         [ 7,  8]]],


       [[[ 5,  6],
         [ 9, 10]],

        [[ 6,  7],
         [10, 11]],

        [[ 7,  8],
         [11, 12]]]])

In [171]:
# 3차원 이미지
image = np.random.rand(512,512,3)

In [194]:
image.shape

(512, 512, 3)

In [188]:
patches = patchify(image, (2,2,3), step=1) # patch shape [2,2,3]
print(patches.shape) # (511, 511, 1, 2, 2, 3). Total patches created: 511x511x1

(511, 511, 1, 2, 2, 3)


In [189]:
patches

array([[[[[[0.19119519, 0.6854484 , 0.52153674],
           [0.64902776, 0.4827506 , 0.6143181 ]],

          [[0.70840557, 0.50316973, 0.31242931],
           [0.74800047, 0.11793744, 0.46006623]]]],



        [[[[0.64902776, 0.4827506 , 0.6143181 ],
           [0.86442841, 0.53837552, 0.81846821]],

          [[0.74800047, 0.11793744, 0.46006623],
           [0.91398669, 0.38240221, 0.06225093]]]],



        [[[[0.86442841, 0.53837552, 0.81846821],
           [0.3083967 , 0.63680657, 0.22036638]],

          [[0.91398669, 0.38240221, 0.06225093],
           [0.11017373, 0.33968149, 0.96613409]]]],



        ...,



        [[[[0.25013016, 0.59539438, 0.25603071],
           [0.02158842, 0.78326357, 0.14665247]],

          [[0.76302624, 0.70899694, 0.9405028 ],
           [0.31509971, 0.91743689, 0.71971732]]]],



        [[[[0.02158842, 0.78326357, 0.14665247],
           [0.92603024, 0.55804819, 0.26224408]],

          [[0.31509971, 0.91743689, 0.71971732],
           [0.42974

In [29]:
# # assert (가정 설정문)은 어떤 조건이 True임을 보증하기 위해서 사용

# assert patches.shape == (511, 511, 1, 2, 2, 3)
# reconstructed_image = unpatchify(patches, image.shape)
# print(reconstructed_image.shape) # (512, 512, 3)

# assert (reconstructed_image == image).all()

(512, 512, 3)


### 참고 코드

In [1]:
large_image_stack = tiff.imread('small_dataset_for_training/images/12_training_mito_images.tif')
large_mask_stack = tiff.imread('small_dataset_for_training/masks/12_training_mito_masks.tif')

for img in range(large_image_stack.shape[0]):

    large_image = large_image_stack[img]
    
    # 2차원 이미지를 더 작은 단위로 분할
    patches_img = patchify(large_image, (256, 256), step=256)  #Step=256 for 256 patches means no overlap
    
    for i in range(patches_img.shape[0]):
        for j in range(patches_img.shape[1]):
            
            single_patch_img = patches_img[i,j,:,:]
            tiff.imwrite('patches/images/' + 'image_' + str(img) + '_' + str(i)+str(j)+ ".tif", single_patch_img)
            

for msk in range(large_mask_stack.shape[0]):
     
    large_mask = large_mask_stack[msk]
    
    patches_mask = patchify(large_mask, (256, 256), step=256)  #Step=256 for 256 patches means no overlap
    

    for i in range(patches_mask.shape[0]):
        for j in range(patches_mask.shape[1]):
            
            single_patch_mask = patches_mask[i,j,:,:]
            tiff.imwrite('patches/masks/' + 'mask_' + str(msk) + '_' + str(i)+str(j)+ ".tif", single_patch_mask)
            single_patch_mask = single_patch_mask / 255.
            

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\small_dataset_for_training\\images\\12_training_mito_images.tif'